package cli

import (
	"time"

	"github.com/mfateev/temporal-agent-harness/internal/models"
	"github.com/mfateev/temporal-agent-harness/internal/skills"
	"github.com/mfateev/temporal-agent-harness/internal/workflow"
)

// WorkflowStartedMsg is sent when a workflow has been started or resumed.
type WorkflowStartedMsg struct {
	WorkflowID string
	Items      []models.ConversationItem // Non-nil only for resume
	Status     workflow.TurnStatus       // Non-zero only for resume
	IsResume   bool
}

// WorkflowStartErrorMsg is sent when starting/resuming a workflow fails.
type WorkflowStartErrorMsg struct {
	Err error
}

// PollResultMsg wraps a PollResult from the polling goroutine.
type PollResultMsg struct {
	Result PollResult
}

// WatchResultMsg wraps a WatchResult from the blocking watcher goroutine.
type WatchResultMsg struct {
	Result WatchResult
}

// UserInputSentMsg is sent after user input has been successfully sent.
// Contains a full StateUpdateResponse (items + status) so the CLI can render
// immediately without an extra round-trip.
type UserInputSentMsg struct {
	Response workflow.StateUpdateResponse
}

// UserInputErrorMsg is sent when sending user input fails.
type UserInputErrorMsg struct {
	Err error
}

// InterruptSentMsg is sent after an interrupt has been successfully sent.
type InterruptSentMsg struct{}

// InterruptErrorMsg is sent when sending an interrupt fails.
type InterruptErrorMsg struct {
	Err error
}

// ShutdownSentMsg is sent after a shutdown has been successfully sent.
type ShutdownSentMsg struct{}

// ShutdownErrorMsg is sent when sending a shutdown fails.
type ShutdownErrorMsg struct {
	Err error
}

// ApprovalSentMsg is sent after an approval response has been sent.
type ApprovalSentMsg struct{}

// ApprovalErrorMsg is sent when sending an approval response fails.
type ApprovalErrorMsg struct {
	Err error
}

// EscalationSentMsg is sent after an escalation response has been sent.
type EscalationSentMsg struct{}

// EscalationErrorMsg is sent when sending an escalation response fails.
type EscalationErrorMsg struct {
	Err error
}

// SessionCompletedMsg is sent when the workflow completes.
type SessionCompletedMsg struct {
	Result *workflow.WorkflowResult // nil if unavailable
}

// SessionErrorMsg is sent when the workflow encounters an unrecoverable error.
type SessionErrorMsg struct {
	Err error
}

// UserInputQuestionSentMsg is sent after a user input question response has been sent.
type UserInputQuestionSentMsg struct{}

// UserInputQuestionErrorMsg is sent when sending a user input question response fails.
type UserInputQuestionErrorMsg struct {
	Err error
}

// CompactSentMsg is sent after a compact request has been successfully sent.
type CompactSentMsg struct{}

// CompactErrorMsg is sent when sending a compact request fails.
type CompactErrorMsg struct {
	Err error
}

// ModelUpdateSentMsg is sent after a model update has been successfully sent.
type ModelUpdateSentMsg struct {
	Provider string
	Model    string
}

// ModelUpdateErrorMsg is sent when sending a model update fails.
type ModelUpdateErrorMsg struct {
	Err error
}

// PlanRequestAcceptedMsg is sent when the plan_request Update is accepted and
// the planner child workflow has started.
type PlanRequestAcceptedMsg struct {
	AgentID    string
	WorkflowID string
}

// PlanRequestErrorMsg is sent when the plan_request Update fails.
type PlanRequestErrorMsg struct {
	Err error
}

// PlannerCompletedMsg is sent when the planner child workflow completes and
// its plan text has been extracted.
type PlannerCompletedMsg struct {
	PlanText string
}

// ModelsFetchedMsg is sent when the background model-list fetch completes.
type ModelsFetchedMsg struct {
	Models []modelOption
	Err    error
}

// SuggestionPollMsg is sent after a delayed poll to pick up the suggestion
// generated by the workflow after turn completion.
type SuggestionPollMsg struct {
	Suggestion string
}

// DiffResultMsg is sent when the background git diff completes.
type DiffResultMsg struct {
	Output string
}

// ReviewResultMsg is sent when the background git diff for /review completes.
type ReviewResultMsg struct {
	Output string
}

// InitResultMsg is sent when the /init scaffold completes.
type InitResultMsg struct {
	Path          string
	Created       bool
	AlreadyExists bool
}

// InitErrorMsg is sent when the /init scaffold fails.
type InitErrorMsg struct {
	Err error
}

// ApprovalModeUpdateSentMsg is sent after an approval mode update succeeds.
type ApprovalModeUpdateSentMsg struct {
	Mode string
}

// ApprovalModeUpdateErrorMsg is sent when an approval mode update fails.
type ApprovalModeUpdateErrorMsg struct {
	Err error
}

// PersonalityUpdateSentMsg is sent after a personality update succeeds.
type PersonalityUpdateSentMsg struct {
	Personality string
}

// PersonalityUpdateErrorMsg is sent when a personality update fails.
type PersonalityUpdateErrorMsg struct {
	Err error
}

// NewSessionStartedMsg is sent when a /new session has been started.
type NewSessionStartedMsg struct {
	WorkflowID string
}

// NewSessionErrorMsg is sent when starting a new session fails.
type NewSessionErrorMsg struct {
	Err error
}

// McpToolsResultMsg is sent when the MCP tools query completes.
type McpToolsResultMsg struct {
	Tools []workflow.McpToolSummary
}

// McpToolsErrorMsg is sent when the MCP tools query fails.
type McpToolsErrorMsg struct {
	Err error
}

// ExecSessionsResultMsg is sent when the exec sessions list is fetched.
type ExecSessionsResultMsg struct {
	Sessions []workflow.ExecSessionSummary
}

// ExecSessionsErrorMsg is sent when listing exec sessions fails.
type ExecSessionsErrorMsg struct {
	Err error
}

// CleanExecSessionsResultMsg is sent when exec sessions are cleaned.
type CleanExecSessionsResultMsg struct {
	Closed int
}

// CleanExecSessionsErrorMsg is sent when cleaning exec sessions fails.
type CleanExecSessionsErrorMsg struct {
	Err error
}

// HarnessSessionsMsg is returned when the harness's session list is fetched successfully.
type HarnessSessionsMsg struct {
	Sessions []workflow.SessionEntry
}

// HarnessSessionsErrorMsg is returned when fetching harness sessions fails.
type HarnessSessionsErrorMsg struct {
	Err error
}

// SessionListEntry is one row in the session picker.
type SessionListEntry struct {
	WorkflowID string
	StartTime  time.Time
	Status     string // "running", "completed", "errored", etc.
	Name       string // User-assigned session name (from /rename)
	Model      string // Model identifier
}

// HarnessSessionsListMsg is sent when the session list fetch completes.
type HarnessSessionsListMsg struct {
	Entries []SessionListEntry
	Err     error
}

// SkillsListResultMsg is sent when the skills list query completes.
type SkillsListResultMsg struct {
	Skills []skills.SkillMetadata
}

// SkillsListErrorMsg is sent when the skills list query fails.
type SkillsListErrorMsg struct {
	Err error
}

// SkillToggleSentMsg is sent after a skill toggle update succeeds.
type SkillToggleSentMsg struct {
	SkillPath string
	Enabled   bool
}

// SkillToggleErrorMsg is sent when a skill toggle update fails.
type SkillToggleErrorMsg struct {
	Err error
}

// SessionNameSentMsg is sent after a session name update succeeds.
type SessionNameSentMsg struct {
	Name string
}

// SessionNameErrorMsg is sent when a session name update fails.
type SessionNameErrorMsg struct {
	Err error
}
