package cli

import (
	"github.com/mfateev/codex-temporal-go/internal/models"
	"github.com/mfateev/codex-temporal-go/internal/workflow"
)

// WorkflowStartedMsg is sent when a workflow has been started or resumed.
type WorkflowStartedMsg struct {
	WorkflowID string
	Items      []models.ConversationItem // Non-nil only for resume
	Status     workflow.TurnStatus       // Non-zero only for resume
	IsResume   bool
}

// WorkflowStartErrorMsg is sent when starting/resuming a workflow fails.
type WorkflowStartErrorMsg struct {
	Err error
}

// PollResultMsg wraps a PollResult from the polling goroutine.
type PollResultMsg struct {
	Result PollResult
}

// UserInputSentMsg is sent after user input has been successfully sent.
type UserInputSentMsg struct {
	TurnID string
}

// UserInputErrorMsg is sent when sending user input fails.
type UserInputErrorMsg struct {
	Err error
}

// InterruptSentMsg is sent after an interrupt has been successfully sent.
type InterruptSentMsg struct{}

// InterruptErrorMsg is sent when sending an interrupt fails.
type InterruptErrorMsg struct {
	Err error
}

// ShutdownSentMsg is sent after a shutdown has been successfully sent.
type ShutdownSentMsg struct{}

// ShutdownErrorMsg is sent when sending a shutdown fails.
type ShutdownErrorMsg struct {
	Err error
}

// ApprovalSentMsg is sent after an approval response has been sent.
type ApprovalSentMsg struct{}

// ApprovalErrorMsg is sent when sending an approval response fails.
type ApprovalErrorMsg struct {
	Err error
}

// EscalationSentMsg is sent after an escalation response has been sent.
type EscalationSentMsg struct{}

// EscalationErrorMsg is sent when sending an escalation response fails.
type EscalationErrorMsg struct {
	Err error
}

// SessionCompletedMsg is sent when the workflow completes.
type SessionCompletedMsg struct {
	Result *workflow.WorkflowResult // nil if unavailable
}

// SessionErrorMsg is sent when the workflow encounters an unrecoverable error.
type SessionErrorMsg struct {
	Err error
}

// UserInputQuestionSentMsg is sent after a user input question response has been sent.
type UserInputQuestionSentMsg struct{}

// UserInputQuestionErrorMsg is sent when sending a user input question response fails.
type UserInputQuestionErrorMsg struct {
	Err error
}

// CompactSentMsg is sent after a compact request has been successfully sent.
type CompactSentMsg struct{}

// CompactErrorMsg is sent when sending a compact request fails.
type CompactErrorMsg struct {
	Err error
}

// ModelUpdateSentMsg is sent after a model update has been successfully sent.
type ModelUpdateSentMsg struct {
	Provider string
	Model    string
}

// ModelUpdateErrorMsg is sent when sending a model update fails.
type ModelUpdateErrorMsg struct {
	Err error
}

// PlanRequestAcceptedMsg is sent when the plan_request Update is accepted and
// the planner child workflow has started.
type PlanRequestAcceptedMsg struct {
	AgentID    string
	WorkflowID string
}

// PlanRequestErrorMsg is sent when the plan_request Update fails.
type PlanRequestErrorMsg struct {
	Err error
}

// PlannerCompletedMsg is sent when the planner child workflow completes and
// its plan text has been extracted.
type PlannerCompletedMsg struct {
	PlanText string
}

// ModelsFetchedMsg is sent when the background model-list fetch completes.
type ModelsFetchedMsg struct {
	Models []modelOption
	Err    error
}

// SuggestionPollMsg is sent after a delayed poll to pick up the suggestion
// generated by the workflow after turn completion.
type SuggestionPollMsg struct {
	Suggestion string
}
